version: "3.9"
services:
  backend:
    build: .
    image: medistream-backend:v4
    container_name: medistream-backend
    ports:
      - "8080:8080"
    networks:
      - medistream-network
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  worker:
    image: medistream-backend:v4
    container_name: medistream-worker
    command: ["./worker"]
    env_file:
      - .env
    networks:
      - medistream-network
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15
    container_name: medistream-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - medistream-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: medistream-redis
    ports:
      - "6379:6379"
    networks:
      - medistream-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: medistream-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - medistream-network

  grafana:
    image: grafana/grafana:10.1.1
    container_name: medistream-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - medistream-network
    depends_on:
      - prometheus

volumes:
  db_data:

networks:
  medistream-network:
    driver: bridge
