version: "3.9"

services:
  backend:
    build: .
    container_name: medistream-backend
    ports:
      - "8080:8080"
    networks:
      - medistream-network
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - redis

  worker:
    build: .
    container_name: medistream-worker
    command: ["./worker"]
    env_file:
      - .env
    networks:
      - medistream-network
    restart: on-failure
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: medistream-redis
    ports:
      - "6379:6379"
    networks:
      - medistream-network

  prometheus:
    image: prom/prometheus:latest
    container_name: medistream-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - medistream-network

  grafana:
    image: grafana/grafana:10.1.1
    container_name: medistream-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - medistream-network
    depends_on:
      - prometheus

networks:
  medistream-network:
    driver: bridge
