apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-v2:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            # Postgres (through PGbouncer)
            - name: DB_HOST
              value: pgbouncer.database.svc.cluster.local
            - name: DB_PORT
              value: "6432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: mydb
            - name: DB_SSLMODE
              value: disable

            # Redis
            - name: REDIS_HOST
              value: redis.database.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"

            # Other environment
            - name: CORS_ALLOWED_ORIGINS
              value: "*"
            - name: LOG_LEVEL
              value: "info"
            - name: APP_ENV
              value: "debug"
            - name: JWT_SECRET
              value: "KNCNGm8ysrli0y3tJ1AZObjcke+U3038LeOl2GZAMho="
            - name: GIN_MODE
              value: "debug"
            - name: MIGRATIONS_DIR
              value: "./migrations"

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
