global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: medistream-backend
    static_configs:
      - targets: ["medistream-backend:8080"]
      
  - job_name: medistream-backend-tests
    static_configs:
      - targets: ["host.docker.internal:2112"]
